### ISSUE TITLE
Replace a Sweave vignette with an R Markdown vignette

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/sweave2rmd#32]
Hello Outreachy applicants!

*Note: This task can be complete by multiple Outreachy applicants.*

This second contribution task builds on what you've learned by working on a Bioconductor package vignette.

**Prep Work**

* Please read our [contribution document](https://bioconductor.github.io/sweave2rmd/articles/contribute.html), which gives a good overview of the project plus the general workflow. In particular, you will be performing the tasks from *Create the R Markdown (.Rmd) vignette and Remove the Sweave vignette (.Rnw)*.
* Install [pandoc](https://pandoc.org/)

**Contribution Task**

Make a pull request replacing a Sweave vignette with an R Markdown vignette.

1. Select a vignette from our [project board](https://github.com/orgs/Bioconductor/projects/2/views/2?filterQuery=Notes%3AOutreachy&visibleFields=%5B%22Title%22%2C5132918%2C%22Status%22%2C13926192%5D) that is labeled 'Easy' or 'Medium', set to 'Todo' and are unassigned. 
2. Write a comment with the path of the vignette you'd like to do--e.g., `BiocParallel/vignettes/Introduction_To_BiocParallel.Rnw` to `@Bioconductor/sweave2rmd`. We will write your GitHub username as 'Assigned' and set 'Last Modified' to today.x
4. Perform the steps in [Create the R Markdown (.Rmd) vignette and Remove the Sweave vignette (.Rnw)](https://bioconductor.github.io/sweave2rmd/articles/contribute.html#create-the-r-markdown--rmd-vignette-and-remove-the-sweave-vignette--rnw). **Note: You do not need to contact the maintainers to work on this set of vignettes as they have either been previously contact OR they are maintained by the Bioconductor Core Team.**
5. Make sure that you request a review by writing `@Bioconductor/sweave2rmd` in a comment so that we can review your pull request. For example, `@Bioconductor/sweave2rmd please review my contribution for Outreachy`.
6. If you receive any feedback requesting changes, please address them.

Tip: You can find the PDF you'll be replacing by visiting the landing page for the package under *Documents*. You can look up the package at [Bioconductor Software Packages](https://bioconductor.org/packages/devel/BiocViews.html#___Software).

If your pull request is good, it will be merged into Bioconductor!

Remember to record your contributions in Outreachy at https://www.outreachy.org/outreachy-december-2022-internship-round/communities/bioconductor/convert-sweave-vignettes-to-r-markdown/contributions/.

**Comment by Cee-tech21** [comment]
Hola @jwokaty I will like to work on this task please.

**Comment by BeatriceTA** [comment]
Hi, @jwokaty 
Thank you for the detailed explanation of how to make a contribution. I intend to work on this project and make my contribution  soonest

**Comment by niyolynate** [comment]
Hello, @jwokaty 
I intend to work on this issue, am an Outreacy applicant. starting as soon as possible.

**Comment by niyolynate** [comment]
Hi,

I'm  an outreachy applicant. tis is my Rmarkdown sample. 
~code~ [[Rmark Sample.txt](https://github.com/Bioconductor/sweave2rmd/files/9749805/Rmark.Sample.txt)](https://bioconductor.github.io/sweave2rmd/articles/contribute.html)
applicant.


Thanks for your time.
Contact the [NiyoLynate](https://github.com/niyolynate) 

am still reading thru the documents am soon changing a bigger doc.

**Comment by niyolynate** [comment]
https://bioconductor.org/packages/release/bioc/html/biocViews.html
Hi,
Hi, i intend to edit this package to a Rmarkdown, [[Sweave2Rmd](https://github.com/Bioconductor/sweave2rmd)](https://bioconductor.org/packages/release/bioc/html/biocViews.html)
and we're trying to replace all Bioconductor Sweave vignettes with R Markdown
vignettes. Would you be willing to accept a pull request converting
__vignette_name__ for __package_name__ from one of our volunteers? We'll ask
you to review and accept the pull request. You'll also need to bump the
version number in your DESCRIPTION file so that the build machines will
recognize that a new version is available.

Thanks for your time.

**Comment by niyolynate** [comment]
Please Guide me am i on the right truck choosing this package to edit?
``Replace a Sweave vignette with an R Markdown vignette #32``

[https://bioconductor.org/packages/release/bioc/html/biocViews.html]

**Comment by hsadia538** [comment]
Hi @jwokaty 
I have created a PR under biobase package for this task

**Comment by jwokaty** [comment]
Hi @niyolynate, I've updated the instructions above with the link to the project board where you can select a vignette to work on.

**Comment by hsadia538** [comment]
Hi @jwokaty ,
I have opened another PR for `Biobase/vignettes/BiobaseDevelopment.Rnw` Can you please update the board ?
Also, I want to get assigned to `Biostrings/vignettes/matchprobes.Rnw`. Thanks :)

**Comment by BeatriceTA** [comment]
Hello @jwokaty,
Can you assign me to graph/vignettes/graph.Rnw on the board? I intend to work on it.
Thank you

**Comment by phyleria** [comment]
Hi @jwokaty 

Can you kindly assign me to   `BiocParallel/Vignettes/Introduction_ToBiocParallel.Rnw`  as I'm working on it. Thanks!

**Comment by jwokaty** [comment]
Hi, I just wanted to clarify that you do not need to contact any maintainers from the filtered [project board](https://github.com/orgs/Bioconductor/projects/2/views/2?filterQuery=Notes%3AOutreachy&visibleFields=%5B%22Title%22%2C5132918%2C%22Status%22%2C13926192%5D). We have already sorted this out because it usually takes time to get approval and we wanted to make sure you would have time to focus on your contribution without any delays. When you start on your vignette, you start from step 3 above [Create the R Markdown (.Rmd) vignette and Remove the Sweave vignette (.Rnw)](https://bioconductor.github.io/sweave2rmd/articles/contribute.html#create-the-r-markdown--rmd-vignette-and-remove-the-sweave-vignette--rnw).

**Comment by phyleria** [comment]
> Hi, I just wanted to clarify that you do not need to contact any maintainers from the filtered [project board](https://github.com/orgs/Bioconductor/projects/2/views/2?filterQuery=Notes%3AOutreachy&visibleFields=%5B%22Title%22%2C5132918%2C%22Status%22%2C13926192%5D). We have already sorted this out because it usually takes time to get approval and we wanted to make sure you would have time to focus on your contribution without any delays. When you start on your vignette, you start from step 3 above [Create the R Markdown (.Rmd) vignette and Remove the Sweave vignette (.Rnw)](https://bioconductor.github.io/sweave2rmd/articles/contribute.html#create-the-r-markdown--rmd-vignette-and-remove-the-sweave-vignette--rnw).

Thank you for clarifying this @jwokaty !

**Comment by calvnce** [comment]
Hello @jwokaty,
Could you consider assigning me the [S4Vectors/vignettes/S4VectorsOverview.Rnw] on the board? I intend to work on it.
Thank you

**Comment by Chisomgold** [comment]
Hi @jwokaty 
Can you assign me to ` graph/vignettes/GraphClass.Rnw`? I am working on it. Thank you.

**Comment by jwokaty** [comment]
Hi everyone, 

After you finish your pull request, can you put the link here so that I can update the project board? I just want to make sure that I don't miss anyone's PR. Thanks!

**Comment by niyolynate** [comment]
Thank you @jwokaty for the guidance. I will start right away.

**Comment by Fernweh-g** [comment]
Hi @jwokaty
Could you assign me `graph/vignettes/clusterGraph.Rnw` ? Thank you :)

**Comment by niyolynate** [comment]
Hello @jwokaty
i have pushed my first pull request concerning the issue, Please review my PR.

**Comment by jwokaty** [comment]
@phyleria `BiocParallel_BatchtoolsParam.Rnw` is not available to be worked on (someone else worked on it). You're welcome to choose another from the board.

**Comment by phyleria** [comment]
Sure no problem 👍
I'll look for another vignette, thank you!

**Comment by hsadia538** [comment]
Hi.
I have made a PR for `Biostrings/matchprobes.Rnw`. [Here](https://github.com/Bioconductor/Biostrings/pull/86)
Please assign me to `GenomicRanges/vignettes/ExtendingGenomicRanges.Rnw` , I am working on it.

**Comment by Chisomgold** [comment]
Hi @jwokaty 

I have made a PR for `graph/vignettes/MulitGraphClass.Rnw` [here](https://github.com/Bioconductor/graph/pull/10)
Please assign me to `genefilter/vignettes/howtogenefinder.Rnw`. I'm working on it next.

**Comment by phyleria** [comment]
Hello @jwokaty,
Kindly assign me to  the`MLInt_devel.Rnw` vignette

**Comment by jwokaty** [comment]
@Chisomgold Someone is already working on `howtogenefinder`. I requested you make changes to the MultiGraphClass PR. Could I ask you to work on that first before selecting another vignette?

**Comment by hsadia538** [comment]
HI @jwokaty 
I have made a PR for `GenomicRanges/vignettes/ExtendingGenomicRanges.Rnw ` [here](https://github.com/Bioconductor/GenomicRanges/pull/69).
Please assign me to `GenomeInfoDb/vignettes/Accept-organism-for-GenomeInfoDb.Rnw
` , I intent to work on it. Thank you

**Comment by Chisomgold** [comment]
> @Chisomgold Someone is already working on `howtogenefinder`. I requested you make changes to the MultiGraphClass PR. Could I ask you to work on that first before selecting another vignette?

I have made changes. I asked a question about the branch. Is it possible to delete the first branch and make  a PR from the new one? They have the same names though.

**Comment by Chisomgold** [comment]
Hi @jwokaty 

I've made a new PR for MultiGraphClass conversion [here](https://github.com/Bioconductor/graph/pull/11).
I'll work on the changes requested for GraphClass. 

Thank you

**Comment by Chisomgold** [comment]
Hi @jwokaty 

Can I work on another package now?

**Comment by jwokaty** [comment]
@Chisomgold Yes, please select it from the project board and let me know what you're working on.

**Comment by jwokaty** [comment]
Hi everyone! I just wanted to say thanks for your hard work and remind you to please record your contributions at https://www.outreachy.org/outreachy-december-2022-internship-round/communities/bioconductor/convert-sweave-vignettes-to-r-markdown/contributions/. I am a little behind on reviewing contributions, so I appreciate your patience.

**Comment by Chisomgold** [comment]
> @Chisomgold Yes, please select it from the project board and let me know what you're working on.

Alright. Thanks
Can you assign me to `GenomicAlignments/vignettes/WorkingWithAlignedNucleotides.Rnw` @jwokaty

**Comment by phyleria** [comment]
Hi @jwokaty 
I have created a PR for `MLInterfaces/Vignettes/MLint_devel.Rnw`  and here's the [link](https://github.com/vjcitn/MLInterfaces/pull/6)

Kindly assign me to `MLInterfaces/Vignettes/MLprac2_2.Rnw`. Thank you!

**Comment by BerylKanali** [comment]
Hi @jwokaty 
I have created a pull request for `S4Vectors/vignettes/RleTricks.Rnw` [here](Converting RleTricks.Rnw to Rmd #110)
Can you also assign me `S4Vectors/vignettes/S4VectorsOverview.Rnw`?

**Comment by BerylKanali** [comment]
Hi @jwokaty
I have created a pull request for 
`S4Vectors/vignettes/S4VectorsOverview.Rnw` [here](https://github.com/Bioconductor/S4Vectors/pull/111)

**Comment by phyleria** [comment]
Hello @jwokaty 
I have created a PR for `MLprac2_2.Rnw` , please find the link [here](https://github.com/vjcitn/MLInterfaces/pull/9).
Thank you.

**Comment by Chisomgold** [comment]
Hi @jwokaty 

I've created a PR for `GenomicAlignments/vignettes/WorkingWithAlignedNucleotides.Rnw`. Here's the [link](https://github.com/Bioconductor/GenomicAlignments/pull/22).

Thanks

**Comment by phyleria** [comment]
Hello @jwokaty 
Kindly assign me to the `ffpe/vignettes/ffpe.Rnw` vignette. 
Thank you.
