### ISSUE TITLE
Cleaner use of pandoc

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/sweave2rmd#34]
https://github.com/Bioconductor/sweave2rmd/blob/9f6f79ba792214549f63d73e2c2c627102c7cf53/vignettes/contribute.Rmd#L146-L151 might be replaced with
```
pandoc -f latex -t markdown file.Rnw -o file.Rmd
```

A problem with this translation is that unknown LaTex macros are dropped. So for instance in https://github.com/Bioconductor/BiocParallel/blob/master/vignettes/Introduction_To_BiocParallel.Rnw the first few lines of the Introduction

> Numerous approaches are available for parallel computing in \R{}. The
CRAN Task View for high performance and parallel computing provides
useful high-level summaries and package categorization.
\url{http://cran.r-project.org/web/views/HighPerformanceComputing.html}
Most Task View packages cite or identify one or more of \CRANpkg{snow},
\CRANpkg{Rmpi}, \CRANpkg{multicore} or \CRANpkg{foreach} as relevant
parallelization infrastructure. Direct support in \R{} for parallel

are translated to

> Numerous approaches are available for parallel computing in . The CRAN
Task View for high performance and parallel computing provides useful
high-level summaries and package categorization.
<http://cran.r-project.org/web/views/HighPerformanceComputing.html> Most
Task View packages cite or identify one or more of , , or as relevant
parallelization infrastructure. Direct support in for parallel computing
started with release 2.14.0 with inclusion of the package which contains
modified versions of and .

where the LaTeX macros `\R{}` and `\CRANpkg{}` (from the BiocStyle package?) are silently dropped, making it very difficult to get the translation complete.

Using instead the command

```
pandoc -f latex+raw_tex -t markdown file.Rnw -o file.Rmd
```

produces

> Numerous approaches are available for parallel computing in
`\R{}`{=latex}. The CRAN Task View for high performance and parallel
computing provides useful high-level summaries and package
categorization.
<http://cran.r-project.org/web/views/HighPerformanceComputing.html> Most
Task View packages cite or identify one or more of
`\CRANpkg{snow}`{=latex}, `\CRANpkg{Rmpi}`{=latex},
`\CRANpkg{multicore}`{=latex} or `\CRANpkg{foreach}`{=latex} as relevant
parallelization infrastructure. Direct support in `\R{}`{=latex} for
parallel computing started with release 2.14.0 with inclusion of the
`\CRANpkg{parallel}`{=latex} package which contains modified versions of
`\CRANpkg{multicore}`{=latex} and `\CRANpkg{snow}`{=latex}.

so it is easy to spot (and fix, e.g., using find / replace) the things that could not be automatically converted.

I am not very knowledgeable in pandoc, so there might be better solutions.

**Comment by jwokaty** [comment]
I noticed this on vignette that I was reviewing but didn't dig into why this happened. Thank you for this helpful suggestion!

**Comment by vareenrose** [comment]
Hi @mtmorgan and @jwokaty I am an outreachy applicant and I would like to make the outlined changes

**Comment by mcarlsn** [comment]
Thank you so much for the suggestion, @mtmorgan! After testing the command on a few vignettes and looking at alternatives, I think this is the most effective/efficient. I updated the contribute pg to reflect the updated instructions. Appreciate you suggesting it @mtmorgan!
