### ISSUE TITLE
Evaluate use of Rnw2Rmd

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/sweave2rmd#45]
Let's evaluate if we can use https://github.com/LiNk-NY/Rnw2Rmd for conversions. We could do this a few ways, perhaps taking performing a conversion on an Rnw we've done before and comparing that to the method suggested by Martin to see which is closer to the final .Rmd. It might also be valuable to look at the conversion of a complex vignette.

**Comment by jwokaty** [comment]
@LiNk-NY Do you think it would be possible to have @BerylKanali help with the automations or it's something we could work on together? It's something @mtmorgan also brought up in #35 and it would benefit the project.

**Comment by LiNk-NY** [comment]
> Let's evaluate if we can use https://github.com/LiNk-NY/Rnw2Rmd for conversions. We could do this a few ways, perhaps taking performing a conversion on an Rnw we've done before and comparing that to the method suggested by Martin to see which is closer to the final .Rmd. It might also be valuable to look at the conversion of a complex vignette.

The Rnw syntax is expansive and this package does not perform a complete translation but it works for simple vignettes like that in `UniProt.ws`. 
My intention for the package is to see the viability of integrating pandoc lua filters and to clean up via R. 

Yes, certainly Beryl can contribute. Pull requests are welcome. 
Note that if the lua filters are implemented, my guess is that the codebase will change significantly but that is still to be seen.

**Comment by jwokaty** [comment]
We currently use pandoc to automate some of the process. It's not perfect, but that's why we wanted to create lua filters as Martin had also suggested to us. I think we're doing or will be doing similar work.

**Comment by LiNk-NY** [comment]
Ah I see, perhaps we can create a repository with all the lua filters.

**Comment by mtmorgan** [comment]
A Lua filter for BiocStyle commands and Sweave code chunks `<<...>>= ... @` is in this [pull request](https://github.com/LiNk-NY/Rnw2Rmd/pull/2) and can be invoked with `Rnw2Rmd::Rnw2RmdPandoc()`; see the help page `?Rnw2RmdPandoc`.
