### ISSUE TITLE
Sweave2Rmd Knowledge Check

### ISSUE THREAD

**Issue by villafup** [Bioconductor/sweave2rmd#62]
**Welcome Outreachy applicants!**

_Note: Multiple Outreachy applicants can work on this issue._

Please choose this as your first contribution task to the Bioconductor Sweave2Rmd project as it will familiarize you with the R, R Markdown, GitHub processes, documentation, and the Sweave2Rmd conversion process (learn more about Bioconductor [here](https://bioconductor.org/)). 

**Sweave2Rmd Project** 

Sweave2Rmd is a community project to convert Sweave vignettes to Rmd. Currently, there are approximately 900 vignettes .Rnw in software packages. These vignettes do not operate as effectively as .Rmd as they are older, combine latex with R, and compile to PDF whereas .Rmd vignettes compile to HTML, are BiocStyle compatible, and easier to read and maintain. Therefore, the aim of the Sweave2Rmd project is to convert these Sweave vignettes to .Rmd. 

**Prep Work** 

If you're not familiar with R and R Markdown, please learn a little about them. The following links should be sufficient to get you started: [R Primer - Programming basics](https://rstudio.cloud/learn/primers/1.2) or [R Markdown](https://github.com/rstudio/cheatsheets/raw/main/rmarkdown-2.0.pdf). Then you may complete the following steps: 

- Install R
- Install RStudio
- In RStudio or through the terminal, install devtools and BiocManager: 
  `install.packages(c("devtools", "BiocManager"))`
- Read through the [Sweave2Rmd Contribute article](https://bioconductor.github.io/sweave2rmd/articles/contribute.html), which explains step-by-step the process of converting a Sweave document to Rmd. The article will be important for completing this contribution task.  

**Contribution Task** 

After reading the Sweave2Rmd Contribute article, you may complete the [2023 Outreachy Sweave2Rmd Contribution Familiarity Quiz](https://docs.google.com/forms/d/e/1FAIpQLSeoN0ntSD7A33JBCzKZyMm6ZXccKQfNkemTv_8eqWkeUT7kUg/viewform?usp=sf_link). The quiz contains questions about the process of converting a Sweave vignette to Rmd. It is an opportunity to both test your familiarity with the Contribute article and learn how to convert a vignette if you choose to complete the second (optional) contribution task. We expect the quiz to take up to 3 hours to complete. Only your first submission will count. If you have any questions about the quiz, feel free to post on the Sweave2Rmd Outreachy Slack channel. To join the Slack channel, view https://slack.bioconductor.org/ then search for the channel #outreachy. 

Remember to record your contributions in Outreachy at [https://www.outreachy.org/outreachy-may-2023-internship-cohort/communities/bioconductor/convert-sweave-vignettes-to-r-markdown/contributions/](https://www.outreachy.org/outreachy-may-2023-internship-cohort/communities/bioconductor/convert-sweave-vignettes-to-r-markdown/contributions/)

**Comment by Khadeeejah** [comment]
Hi  @villafup 
I am an outreachy intern here i would like to work on this issue. kindly assign it to me. 
thanks

**Comment by jwokaty** [comment]
> Hi @villafup I am an outreachy intern here i would like to work on this issue. kindly assign it to me. thanks

@Khadeeejah Multiple applicants can work on this issue, no assignment needed! :)

**Comment by siddhi-244** [comment]
Will work on this !

**Comment by Reece11** [comment]
Hi @jwokaty 
I am an outreachy intern  , and i am  working  on this!

**Comment by kemicky** [comment]
@jwokaty 
Hello Sir, 
My name is Mary Jones an Outreachy intern and I currently am working on this contribution, may you please assign this to me. thank you for anticipating to give me the opportunity.

**Comment by SunSummoner** [comment]
> **Welcome Outreachy applicants!**
> 
> _Note: Multiple Outreachy applicants can work on this issue._
> 
> Please choose this as your first contribution task to the Bioconductor Sweave2Rmd project as it will familiarize you with the R, R Markdown, GitHub processes, documentation, and the Sweave2Rmd conversion process (learn more about Bioconductor [here](https://bioconductor.org/)).
> 
> **Sweave2Rmd Project**
> 
> Sweave2Rmd is a community project to convert Sweave vignettes to Rmd. Currently, there are approximately 900 vignettes .Rnw in software packages. These vignettes do not operate as effectively as .Rmd as they are older, combine latex with R, and compile to PDF whereas .Rmd vignettes compile to HTML, are BiocStyle compatible, and easier to read and maintain. Therefore, the aim of the Sweave2Rmd project is to convert these Sweave vignettes to .Rmd.
> 
> **Prep Work**
> 
> If you're not familiar with R and R Markdown, please learn a little about them. The following links should be sufficient to get you started: [R Primer - Programming basics](https://rstudio.cloud/learn/primers/1.2) or [R Markdown](https://github.com/rstudio/cheatsheets/raw/main/rmarkdown-2.0.pdf). Then you may complete the following steps:
> 
> * Install R
> * Install RStudio
> * In RStudio or through the terminal, install devtools and BiocManager:
>   `install.packages(c("devtools", "BiocManager"))`
> * Read through the [Sweave2Rmd Contribute article](https://bioconductor.github.io/sweave2rmd/articles/contribute.html), which explains step-by-step the process of converting a Sweave document to Rmd. The article will be important for completing this contribution task.
> 
> **Contribution Task**
> 
> After reading the Sweave2Rmd Contribute article, you may complete the [2023 Outreachy Sweave2Rmd Contribution Familiarity Quiz](https://docs.google.com/forms/d/e/1FAIpQLSeoN0ntSD7A33JBCzKZyMm6ZXccKQfNkemTv_8eqWkeUT7kUg/viewform?usp=sf_link). The quiz contains questions about the process of converting a Sweave vignette to Rmd. It is an opportunity to both test your familiarity with the Contribute article and learn how to convert a vignette if you choose to complete the second (optional) contribution task. We expect the quiz to take up to 3 hours to complete. If you have any questions about the quiz, feel free to post on the Sweave2Rmd Outreachy Slack channel. To join the Slack channel, view https://slack.bioconductor.org/ then search for the channel #outreachy.
> 
> Remember to record your contributions in Outreachy at https://www.outreachy.org/outreachy-may-2023-internship-cohort/communities/bioconductor/convert-sweave-vignettes-to-r-markdown/contributions/

Hi
I am Kritika Verma. I am an Outreachy applicant for the may cohort and I would like to work on this as my first contribution.
Thank you.

**Comment by kemicky** [comment]
Hello please I am trying to claim one of the claim a vigennette, please can you assign this medium to me : summarizeOverlaps.Rnw 
to me . I am unable to assign the project to me.

**Comment by Palaktahlyani** [comment]
Hey @jwokaty 
I am Outreachy intern, working on this project. Hope to get connect with you all.

**Comment by sonali8434** [comment]
Hi @jwokaty
I am an outreachy intern , and i am working on this , My first contribution task is completed currently working on 2nd contribution task.

**Comment by Reece11** [comment]
> Hi @jwokaty I am an outreachy intern , and i am working on this!

hi @jwokaty I  completed the first task moving to completing the second contribution task

**Comment by Merit25** [comment]
> **Welcome Outreachy applicants!**
> 
> _Note: Multiple Outreachy applicants can work on this issue._
> 
> Please choose this as your first contribution task to the Bioconductor Sweave2Rmd project as it will familiarize you with the R, R Markdown, GitHub processes, documentation, and the Sweave2Rmd conversion process (learn more about Bioconductor [here](https://bioconductor.org/)).
> 
> **Sweave2Rmd Project**
> 
> Sweave2Rmd is a community project to convert Sweave vignettes to Rmd. Currently, there are approximately 900 vignettes .Rnw in software packages. These vignettes do not operate as effectively as .Rmd as they are older, combine latex with R, and compile to PDF whereas .Rmd vignettes compile to HTML, are BiocStyle compatible, and easier to read and maintain. Therefore, the aim of the Sweave2Rmd project is to convert these Sweave vignettes to .Rmd.
> 
> **Prep Work**
> 
> If you're not familiar with R and R Markdown, please learn a little about them. The following links should be sufficient to get you started: [R Primer - Programming basics](https://rstudio.cloud/learn/primers/1.2) or [R Markdown](https://github.com/rstudio/cheatsheets/raw/main/rmarkdown-2.0.pdf). Then you may complete the following steps:
> 
> * Install R
> * Install RStudio
> * In RStudio or through the terminal, install devtools and BiocManager:
>   `install.packages(c("devtools", "BiocManager"))`
> * Read through the [Sweave2Rmd Contribute article](https://bioconductor.github.io/sweave2rmd/articles/contribute.html), which explains step-by-step the process of converting a Sweave document to Rmd. The article will be important for completing this contribution task.
> 
> **Contribution Task**
> 
> After reading the Sweave2Rmd Contribute article, you may complete the [2023 Outreachy Sweave2Rmd Contribution Familiarity Quiz](https://docs.google.com/forms/d/e/1FAIpQLSeoN0ntSD7A33JBCzKZyMm6ZXccKQfNkemTv_8eqWkeUT7kUg/viewform?usp=sf_link). The quiz contains questions about the process of converting a Sweave vignette to Rmd. It is an opportunity to both test your familiarity with the Contribute article and learn how to convert a vignette if you choose to complete the second (optional) contribution task. We expect the quiz to take up to 3 hours to complete. If you have any questions about the quiz, feel free to post on the Sweave2Rmd Outreachy Slack channel. To join the Slack channel, view https://slack.bioconductor.org/ then search for the channel #outreachy.
> 
> Remember to record your contributions in Outreachy at https://www.outreachy.org/outreachy-may-2023-internship-cohort/communities/bioconductor/convert-sweave-vignettes-to-r-markdown/contributions/

I am an outreachy intern, I would like to contribute on the first contribution task

**Comment by Dbn-tech** [comment]
Hey @jwokaty
I am Outreachy intern, working on this project. Hope to get connect with you all.

**Comment by mcarlsn** [comment]
> 

FYI @sonali8434 your submitted form was received. You may use the URL to this comment as evidence in the Outreachy application of completing the first contribution. Thanks!

**Comment by mcarlsn** [comment]
> @jwokaty Hello Sir, My name is Mary Jones an Outreachy intern and I currently am working on this contribution, may you please assign this to me. thank you for anticipating to give me the opportunity.

FYI @kemicky your submitted form was received. You may use the URL to this comment as evidence in the Outreachy application of completing the first contribution. Thanks!

**Comment by mcarlsn** [comment]
FYI @Rohit-Satyam your submitted form was received. You may use the URL to this comment as evidence in the Outreachy application of completing the first contribution. Thanks!

**Comment by Dbn-tech** [comment]
Hello @mcarlsn  i also submitted mine, i hope it was received

**Comment by mcarlsn** [comment]
> Hi @villafup I am an outreachy intern here i would like to work on this issue. kindly assign it to me. thanks

FYI @Khadeeejah your submitted form was received. You may use the URL to this comment as evidence in the Outreachy application of completing the first contribution. Thanks!

**Comment by mcarlsn** [comment]
FYI @sirjoka your submitted form was received. You may use the URL to this comment as evidence in the Outreachy application of completing the first contribution. Thanks!

**Comment by mcarlsn** [comment]
FYI @bellatrick your submitted form was received. You may use the URL to this comment as evidence in the Outreachy application of completing the first contribution. Thanks!

**Comment by bellatrick** [comment]
> FYI @bellatrick your submitted form was received. You may use the URL to this comment as evidence in the Outreachy application of completing the first contribution. Thanks!

Thanks a lot, will do!!!

**Comment by mcarlsn** [comment]
> Hello @mcarlsn i also submitted mine, i hope it was received

FYI @Dbn-tech your submitted form was received. You may use the URL to this comment as evidence in the Outreachy application of completing the first contribution. Thanks!

**Comment by kemicky** [comment]
> > @jwokaty Hello Sir, My name is Mary Jones an Outreachy intern and I currently am working on this contribution, may you please assign this to me. thank you for anticipating to give me the opportunity.
> 
> FYI @kemicky your submitted form was received. You may use the URL to this comment as evidence in the Outreachy application of completing the first contribution. Thanks!

@mcarlsn Thank you very much Ma'am/ Sir, I will do so immediately

**Comment by Bukolab99** [comment]
Hi @mcarlsn I just completed the quiz and submited. Please acknowledge!

**Comment by mcarlsn** [comment]
> Hi @mcarlsn I just completed the quiz and submited. Please acknowledge!

FYI @Bukolab99 your submitted form was received. You may use the URL to this comment as evidence in the Outreachy application of completing the first contribution. (FYI you can disregard the notifications that this was closed and reopened - accident!) Thanks

**Comment by kemicky** [comment]
@jwokaty 
Good day everyone: please here is my PR for review:
https://github.com/Bioconductor/Category/pull/4
thank you

**Comment by OpehJanet20** [comment]
@jwokaty Hello Sir, My name is Janet Solomon an Outreachy applicant for may 2023 cohort and I currently am working on this as my first contribution, Please assign this to me. Thank you.

**Comment by mcarlsn** [comment]
> Hello, I am Janet Solomon, an Outreachy applicant for May 2023 cohort. I will like to work on this as my first contribution. Thank you.

Welcome, Janet! You're more than welcome to start the quiz whenever you'd like. It is open to anyone without being explicitly assigned. Please let us know if you have any questions!

**Comment by mcarlsn** [comment]
FYI @maryjon4 your submitted form was received. You may use the URL to this comment as evidence in the Outreachy application of completing the first contribution. Thanks!

**Comment by mcarlsn** [comment]
FYI @viclaty (email user name) your submitted form was received. You may use the URL to this comment as evidence in the Outreachy application of completing the first contribution. Thanks!

**Comment by mcarlsn** [comment]
FYI @sophy (adenijisope) your submitted form was received. You may use the URL to this comment as evidence in the Outreachy application of completing the first contribution. Thanks!

**Comment by Bukolab99** [comment]
> > Hi @mcarlsn I just completed the quiz and submited. Please acknowledge!
> 
> 
> 
> FYI @Bukolab99 your submitted form was received. You may use the URL to this comment as evidence in the Outreachy application of completing the first contribution. (FYI you can disregard the notifications that this was closed and reopened - accident!) Thanks

Hello @mcarlsn I am @viclaty (email username) you've acknowledged my submission over a week ago.

**Comment by mcarlsn** [comment]
> > > Hi @mcarlsn I just completed the quiz and submited. Please acknowledge!
> > 
> > 
> > FYI @Bukolab99 your submitted form was received. You may use the URL to this comment as evidence in the Outreachy application of completing the first contribution. (FYI you can disregard the notifications that this was closed and reopened - accident!) Thanks
> 
> Hello @mcarlsn I am @viclaty (email username) you've acknowledged my submission over a week ago.

Apologies! Crossed wires there.

**Comment by Bukolab99** [comment]
> > > > Hi @mcarlsn I just completed the quiz and submited. Please acknowledge!
> 
> > > 
> 
> > > 
> 
> > > FYI @Bukolab99 your submitted form was received. You may use the URL to this comment as evidence in the Outreachy application of completing the first contribution. (FYI you can disregard the notifications that this was closed and reopened - accident!) Thanks
> 
> > 
> 
> > Hello @mcarlsn I am @viclaty (email username) you've acknowledged my submission over a week ago.
> 
> 
> 
> Apologies! Crossed wires there. 

Not a problem. Have a good day!

**Comment by mcarlsn** [comment]
> > > > > Hi @mcarlsn I just completed the quiz and submited. Please acknowledge!
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > FYI @Bukolab99 your submitted form was received. You may use the URL to this comment as evidence in the Outreachy application of completing the first contribution. (FYI you can disregard the notifications that this was closed and reopened - accident!) Thanks
> > 
> > 
> > > 
> > 
> > 
> > > Hello @mcarlsn I am @viclaty (email username) you've acknowledged my submission over a week ago.
> > 
> > 
> > Apologies! Crossed wires there.
> 
> Not a problem. Have a good day!

You too!

**Comment by devbird007** [comment]
Hi @jwokaty @mcarlsn @villafup 
I completed the first quiz and mentioned it [here](https://github.com/Bioconductor/sweave2rmd/issues/63#issuecomment-1459453314), but I did not know that I would have needed to reference it here at that time so I could reference it when recording my contribution.

Please what do I do?

**Comment by Khadeeejah** [comment]
> Hi @jwokaty @mcarlsn @villafup 
> 
> I completed the first quiz and mentioned it [here](https://github.com/Bioconductor/sweave2rmd/issues/63#issuecomment-1459453314), but I did not know that I would have needed to reference it here at that time so I could reference it when recording my contribution.
> 
> 
> 
> Please what do I do?

You can copy the link to this comment
Or also copy the link to the docs concerning your response in the mail 
@mcarlsn  sent us some week back

**Comment by devbird007** [comment]
> > Hi @jwokaty @mcarlsn @villafup
> > I completed the first quiz and mentioned it [here](https://github.com/Bioconductor/sweave2rmd/issues/63#issuecomment-1459453314), but I did not know that I would have needed to reference it here at that time so I could reference it when recording my contribution.
> > Please what do I do?
> 
> You can copy the link to this comment Or also copy the link to the docs concerning your response in the mail @mcarlsn sent us some week back

By "link to the docs concerning your response in the mail", do you mean the google doc file containing our quiz result that I received from Madelyn?

**Comment by Khadeeejah** [comment]
> > > Hi @jwokaty @mcarlsn @villafup
> 
> > > I completed the first quiz and mentioned it [here](https://github.com/Bioconductor/sweave2rmd/issues/63#issuecomment-1459453314), but I did not know that I would have needed to reference it here at that time so I could reference it when recording my contribution.
> 
> > > Please what do I do?
> 
> > 
> 
> > You can copy the link to this comment Or also copy the link to the docs concerning your response in the mail @mcarlsn sent us some week back
> 
> 
> 
> By "link to the docs concerning your response in the mail", do you mean the google doc file containing our quiz result that I received from Madelyn?

Yes that , however @mcarlsn has already received all our submission and linked our GitHub nanes to our submission. So you are good

**Comment by devbird007** [comment]
Alright thanks

**Comment by mcarlsn** [comment]
> your submitted form was received. You may use the URL to this comment as evidence in the Outreachy application of completing the first contribution. Thanks!

@devbird007 Thanks for posting. In your final application, you may use the link to the previous post or URL for this to show that you completed the first contribution for this project. Thank you for submitting the knowledge check quiz! Please let me know if you have any questions.

**Comment by mcarlsn** [comment]
> Hi @jwokaty @mcarlsn @villafup I completed the first quiz and mentioned it [here](https://github.com/Bioconductor/sweave2rmd/issues/63#issuecomment-1459453314), but I did not know that I would have needed to reference it here at that time so I could reference it when recording my contribution.
> 
> Please what do I do?

@devbird007 Thanks for posting. In your final application, you may use the link to the previous post or URL for this to show that you completed the first contribution for this project. Thank you for submitting the knowledge check quiz! Please let me know if you have any questions.

**Comment by devbird007** [comment]
> > Hi @jwokaty @mcarlsn @villafup I completed the first quiz and mentioned it [here](https://github.com/Bioconductor/sweave2rmd/issues/63#issuecomment-1459453314), but I did not know that I would have needed to reference it here at that time so I could reference it when recording my contribution.
> > Please what do I do?
> 
> @devbird007 Thanks for posting. In your final application, you may use the link to the previous post or URL for this to show that you completed the first contribution for this project. Thank you for submitting the knowledge check quiz! Please let me know if you have any questions.

Thank you
