### ISSUE TITLE
Update Contribution to clarify manual edits

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/sweave2rmd#68]
The current contribution document gives the impression that all that is needed is to run pandoc without errors to generate a successful .Rmd, but this is misleading. In particular, there should be a section to expand on what needs manual correction in steps current 13 and 16. This can include examples of code.

Additionally, there should be another step that considers further how to make code easier to maintain, for example, by using `Reflow Comment` to break up long lines.

**Comment by sonali8434** [comment]
@jwokaty I want to work in this issue please assign me this. Thank you.
