### ISSUE TITLE
Update checklist

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/sweave2rmd#69]
Group similar items on the checklist

Add the following to the checklist:

* Only files necessary for the conversion are included in the pull request. See the [Bioconductor Packages: Development, Maintenance, and Peer Review](https://contributions.bioconductor.org/gitignore.html?q=.gitig#gitignore) for more information.
* Long lines have been broken up and reformatted.
* Code blocks are surrounded by a blank line and  there are no blank lines before the start or after the end of the code within the code block.

The code block checklist item should probably have examples.

There should probably be more thought about what are the characteristics of a successful conversion and how we can identify that within the PR.

**Comment by sonali8434** [comment]
@jwokaty  I want to work on this issue please assign me this.

 Thank you!

**Comment by sonali8434** [comment]
@jwokaty  This is my [PR](https://github.com/Bioconductor/sweave2rmd/pull/70) for this issue. 
also I want to ask can I include this PR in my contribution?

**Comment by sirjoka** [comment]
@jwokaty please can I get ShortRead/vignettes/Overview.Rnw assigned to me. My last PR https://github.com/Bioconductor/OrganismDbi/pull/3 was reviewed by @mcarlsn and it got approved
