### ISSUE TITLE
Let's try and check if Levi's conversion template is working when we create a new branch?

### ISSUE THREAD

**Issue by sonali8434** [Bioconductor/sweave2rmd#85]
Let's try to check if Levi's conversion template (https://github.com/lwaldron/sweave2rmd_conversiontemplate) is working by creating a new branch after cloning the original repository?

**Comment by jwokaty** [comment]
The follow are notes after our pair programming session on Levi's action:

* Let's try to report errors, particularly the "unexpected end of input" error in the PR comment. This means we should get it from the `try` in the previous step.
* Let's also try to put the contributor's commit info in the commit (username, email). We should able to find this in the Github actions documentation.

**Comment by sonali8434** [comment]
PR - https://github.com/waldronlab/sweave2rmd_conversiontemplate/pull/2
